Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/09/2019
Var
// Seção de Declarações das variáveis 
  num,numpri: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(num)
para num de 1 ate 10 faca
numpri<-num/num ou num/1
escreval("os numeros primos sao:"numpri)
fimpara
finalgoritmo








Fimalgoritmo