Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/09/2019
Var
// Seção de Declarações das variáveis 
idade,media,i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
leia(idade)
para i <- 1 ate 999 faca
se (idade=i) entao
media<-i/idade
fimpara
escreval("idade igual a zero "


Fimalgoritmo