Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/09/2019
Var
// Seção de Declarações das variáveis 
num,cont,mult:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont<-0
escreval("digite um numero")
leia(num)
enquanto cont<10 faca
cont<-cont+1
mult<-cont*num
escreval(n,"x",cont,"=",mult)
fimenquanto


Fimalgoritmo