Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/09/2019
Var
// Seção de Declarações das variáveis 
i,num:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("escreva um numero  de 1 a 10")
laia(num)
para i de 0 ate 10 faca
escreval(num "x" i "=" i*num
fimpara
Fimalgoritmo